/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

import "sst"
declare module "sst" {
  export interface Resource {
    "InstantDriveBucketURL": {
      "type": "sst.sst.Linkable"
      "url": string
    }
    "InstantDriveS3Compat": {
      "AccountId": string
      "BucketName": string
      "type": "sst.sst.Linkable"
    }
    "R2_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "R2_ACCESS_KEY_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "InstantDrive": cloudflare.R2Bucket
    "InstantDriveCronHandler": cloudflare.Service
    "InstantDriveSessions": cloudflare.KVNamespace
    "InstantDriveWorker": cloudflare.Service
    "drive/frontend": cloudflare.Service
    "instant/frontend": cloudflare.Service
  }
}

import "sst"
export {}