name = "r2-dec-22"
main = "src/index.ts"
compatibility_date = "2022-11-30"

kv_namespaces = [
    { binding = "AUTH", id = "29142e1096a04753b042d4de4c7fb27d", preview_id = "29142e1096a04753b042d4de4c7fb27d" },
]


[[r2_buckets]]
binding = "B_GALLERY"
bucket_name = "drive-1"
preview_bucket_name = "drive-1"

[[r2_buckets]]
binding = "B_PREVIEWS"
bucket_name = "previews-1"
preview_bucket_name = "previews-1"